"""Regenerates the <noscript> publication list inside index.html.

    python scripts/build-noscript.py

Why: the publication list on the home page is assembled in the browser by
assets/site.js reading data/publications.json, so index.html itself ships with
an empty <div id="publications-list">. A crawler that does not execute
JavaScript therefore sees none of the publications. Google runs JavaScript,
but Google Scholar and various other crawlers largely do not.

This writes a plain, static copy of the list into a <noscript> block. Browsers
with JavaScript ignore it completely; everything else reads it. No build
dependency — plain Python, no packages.

Run after editing data/publications.json. The block between the two marker
comments is replaced wholesale, so hand edits inside it will be lost.
"""

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
DATA = ROOT / "data" / "publications.json"

START = "<!-- BEGIN noscript-publications (generated by scripts/build-noscript.py) -->"
END = "<!-- END noscript-publications -->"

GROUPS = [
    ("journal", "Peer-Reviewed Journal Publications"),
    ("working", "Working Paper"),
    ("other", "Other Publications"),
]


def esc(value):
    return html.escape(str(value), quote=True)


def entry(pub):
    """One publication as a single readable sentence."""
    parts = []

    authors = pub.get("authors")
    if authors:
        names = [a["name"] for a in authors]
        joined = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
        parts.append(esc(joined) + ".")

    title = esc(pub["title"])
    url = pub.get("url")
    parts.append(f'<a href="{esc(url)}">{title}</a>.' if url else f"{title}.")

    if pub.get("institution"):
        parts.append(esc(pub["institution"]) + ".")

    tail = []
    if pub.get("venue"):
        name = "<em>" + esc(pub["venue"]) + "</em>"
        if pub.get("venue_url"):
            name = f'<a href="{esc(pub["venue_url"])}">{name}</a>'
        tail.append(name)
    for key in ("volume", "pages", "publisher", "role"):
        if pub.get(key):
            tail.append(esc(pub[key]))
    tail.append(esc(pub["year"]))
    if pub.get("language"):
        tail.append("(" + esc(pub["language"]) + ")")
    parts.append(", ".join(tail) + ".")

    if pub.get("title_zh"):
        parts.append(esc(pub["title_zh"]))

    # `note` carries inline HTML (<em>, <a>) exactly as site.js renders it, so
    # it is passed through unescaped rather than run through esc().
    if pub.get("note"):
        parts.append(pub["note"])

    # On the page `note_links` renders as a chip in the right-hand column, which
    # has no meaning in a flat list — but the URL still has to reach crawlers,
    # so it becomes a trailing link instead.
    for link in pub.get("note_links") or []:
        parts.append(f'<a href="{esc(link["url"])}">{esc(link["label"])}</a>.')

    return "        <li>" + " ".join(parts) + "</li>"


def main():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    pubs = data["publications"]

    out = [
        START,
        "    <noscript>",
        "      <!-- Static copy of the publication list for clients that do not run",
        "           JavaScript. Regenerate with scripts/build-noscript.py after",
        "           editing data/publications.json. -->",
    ]
    total = 0
    for key, label in GROUPS:
        group = sorted(
            (p for p in pubs if p.get("type") == key),
            key=lambda p: -int(p["year"]),
        )
        if not group:
            continue
        out.append(f"      <h3>{label}</h3>")
        out.append("      <ul>")
        out.extend(entry(p) for p in group)
        out.append("      </ul>")
        total += len(group)
    out.append("    </noscript>")
    out.append("    " + END)

    block = "\n".join(out)
    source = INDEX.read_text(encoding="utf-8")

    if START in source and END in source:
        pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
        updated = pattern.sub(lambda _: block, source, count=1)
    else:
        anchor = '<div id="publications-list"></div>'
        if anchor not in source:
            sys.exit(f"Could not find {anchor} in index.html — nothing changed.")
        updated = source.replace(anchor, anchor + "\n    " + block, 1)

    INDEX.write_text(updated, encoding="utf-8")
    print(f"Wrote {total} publications into the <noscript> block of index.html")


if __name__ == "__main__":
    main()
